name: 'Autocoder Bot Action'
description: 'Generates code from GitHub Issues using OpenAI and creates a Pull Request'
author: 'autocoder-bot'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token for API access'
    required: true
  REPOSITORY:
    description: 'The repository (owner/repo)'
    required: true
  ISSUE_NUMBER:
    description: 'The issue number to process'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
  SCRIPT_PATH:
    description: 'Path to the bash script'
    required: true
    default: 'scripts/script.sh'
  LABEL:
    description: 'Label to apply to the PR'
    required: true
    default: 'autocoder-bot'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make script executable
      shell: bash
      run: chmod +x ${{ inputs.SCRIPT_PATH }}

    - name: Run Autocoder Script
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run: |
        ./${{ inputs.SCRIPT_PATH }} \
        "${{ inputs.GITHUB_TOKEN }}" \
        "${{ inputs.REPOSITORY }}" \
        "${{ inputs.ISSUE_NUMBER }}" \
        "$OPENAI_API_KEY"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        commit-message: "Autocoder: code for issue #${{ inputs.ISSUE_NUMBER }}"
        title: "Autocoder Suggestions for Issue #${{ inputs.ISSUE_NUMBER }}"
        body: "Generated by Autocoder Bot."
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
        base: main
        labels: ${{ inputs.LABEL }}
        author: "autocoder-bot <actions@github.com>"
        committer: "autocoder-bot <actions@github.com>"
        add-paths: |
          autocoder-bot/*
